### ISSUE TITLE
Module is broken

### ISSUE THREAD

**Issue by Giorgio68** [simplesamlphp/simplesamlphp-module-adfs#11]
I installed the module using composer, but it's pretty broken. Trying to display metadata just gives a: "Error 500", and when trying to authenticate it'll give this exception: "Template: Could not find template file [adfs:postResponse.twig]". I checked, and the template is present.
I'm running simplesamlphp v1.19.4, php version 7.4.3 and ubuntu 20.04LTS

**Comment by tvdijen** [comment]
What version of the module are you using?

**Comment by Giorgio68** [comment]
When using composer, it says "Installing simplesamlphp/simplesamlphp-module-adfs (v1.0.4)"

**Comment by tvdijen** [comment]
I just installed & configured it, and it works like a charm...

**Comment by Giorgio68** [comment]
I tried reinstalling simplesamlphp altogether, following the instructions on simplesamlphp.org, and I still run into the same error. Could you tell me how you installed the module?

**Comment by tvdijen** [comment]
Nothing special, just a composer install

**Comment by tvdijen** [comment]
Ah, now I _am_ able to reproduce this.. I didn't realize you were still using the old UI..  Let's see if I can fix this

**Comment by tvdijen** [comment]
v1.0.8 should fix things for you
