### ISSUE TITLE
License is LGPL-2.1 or LGPL-3.0

### ISSUE THREAD

**Issue by bodorjzsolt** [simplesamlphp/simplesamlphp-module-adfs#13]
LGPL-3.0 is listed in LICENSE file, but LGPL-2.1 is shown as main license by git. Which would be the main license?

**Comment by tvdijen** [comment]
It's LGPL-2.1! Thanks for reporting this

**Comment by tvdijen** [comment]
I think you saw the 3.0 license in the `release-1.0` branch, right?  We had already fixed it in `master`

**Comment by bodorjzsolt** [comment]
Yes, I saw it in 1.0.8-  thank you for clarifying this!
