### ISSUE TITLE
wrong filename javascript asset

### ISSUE THREAD

**Issue by wimhaan** [simplesamlphp/simplesamlphp-module-adfs#3]
In the module adfs when using the new ui ('usenewui' => true) the adfs module uses postResponse.js but the file is called <saml-instance>modules/adfs/www/assets/js/postReponse.js.
Missing 's' between Re and ponse.js

Tested on version 1.8.5

**Comment by tvdijen** [comment]
Good catch! Thanks @wimhaan!

**Comment by tvdijen** [comment]
Fixed in 425e5eb
Tagged v0.9.6
