### ISSUE TITLE
ADFS Post response should exit

### ISSUE THREAD

**Issue by pradtke** [simplesamlphp/simplesamlphp-module-adfs#4]
When we've been testing v1.0.2 module we get a weird behavior where the ADFS module post a response AND shows an about "Code should never be reached". I believe this is because the response code below

https://github.com/simplesamlphp/simplesamlphp-module-adfs/blob/10fd1c9045c7e3e1aeda62b0d081e127a06deb76/lib/IdP/ADFS.php#L201-L210

is different from `HTTP::submitPOSTData` which calls exit(0) after running.

The ADFS response does not call exit() which results in code in `prp.php` to continue to run.

Adding exit() into ADFS class works fine in our test environment. I was looking to make a PR but I see master has moved to Symfony controller, which I'm not familiar with.  I think this issue wouldn't exist in master since the controller is returning a streamed response.

Should we make a v1.0.3 that has a fix for this issue, and the cherry-picked mis-named file commit  (https://github.com/simplesamlphp/simplesamlphp-module-adfs/commit/a2973512bcbb515141b7a9bfee3b1cffb0e7aead)  and any other issues we uncover with our testing?

**Comment by tvdijen** [comment]
HI Patrick! Thanks for reporting this!
It is indeed a bug and for some reason the [exit](https://github.com/simplesamlphp/simplesamlphp/blob/ab7ca8e3804416d6795f31171b0c1eb2da800607/modules/adfs/lib/IdP/ADFS.php#L149) fell off when rewriting the method to use Twig-templates. I've tagged a new v1.0.3 release to solve this (and branched of into a `release-1.0`-branch to receive your PRs, should you find any other bugs)

**Comment by pradtke** [comment]
Thanks @tvdijen!
