### ISSUE TITLE
Missing return types causing issues on php 7.4 with ssp v1.19.1

### ISSUE THREAD

**Issue by wisebaldone** [simplesamlphp/simplesamlphp-module-adfs#9]
Most of this commit needs to be applied to have a working install of the ADFS module included in the distributed v1.19.1 available on the website.

Installation: Ubuntu:latest docker container with php7.4
SSP Version: 1.19.1

**Comment by tvdijen** [comment]
Thanks @wisebaldone ! But what commit are you referring to?

**Comment by wisebaldone** [comment]
ahh, sorry tvdijen, https://github.com/simplesamlphp/simplesamlphp-module-adfs/commit/5393015c8eb637645cf7b9433f314fe4b38809af 

Will note the xml view of the metadata seems to not be able to find the metadata.php but is less of an issue since the standard metadata url functions fine.

**Comment by tvdijen** [comment]
I think v0.9.7 solves the typehint-issue.. Can you try it? And could you share the error you get when accessing the xml metadata?

**Comment by wisebaldone** [comment]
v0.9.7 works to at least display the metadata, havnt got a wsfed sp setup yet. 

Also the error for rendering the idp metadata as xhtml shows this:

https://some.domain/simplesamlphp/module.php/adfs/idp/metadata.php?output=xhtml



SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:20 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Error: Call to a member function render() on null
Backtrace:
4 lib/SimpleSAML/XHTML/Template.php:524 (SimpleSAML\XHTML\Template::getContents)
3 lib/SimpleSAML/XHTML/Template.php:541 (SimpleSAML\XHTML\Template::send)
2 modules/adfs/www/idp/metadata.php:15 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

**Comment by tvdijen** [comment]
That one's also fixed in v0.9.8...

**Comment by wisebaldone** [comment]
LGTM @tvdijen
